version: '3'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data