appConfig:
  theme: one-dark
  layout: auto
  iconSize: medium
  language: pt
  customCss: >-
    @media (min-width: 1780px) { .home
    .item-group-container:not(.item-size-large) { grid-template-columns:
    repeat(3, 1fr); } } .home .item-group-container.item-size-large
    .item-group-grid, .home .item-group-container.orientation-vertical
    .item-group-grid { display: flex !important; }
  customColors:
    one-dark:
      primary: '#c5cad3'
      background: '#282c33'
      background-darker: '#1c1f23'
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    customSearchEngine: https://duckduckgo.com/?q=
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: true
pageInfo:
  title: Home Lab
  description: ''
  navLinks:
    - title: GitHub
      path: https://github.com/audryus
      target: sametab
    - title: gMail
      path: https://mail.google.com
      target: sametab
    - title: LinkedIn
      path: https://www.linkedin.com/feed/
      target: sametab
  footerText: ''
sections:
  - name: Media & Entertainment
    icon: fas fa-photo-video
    displayData:
      sortBy: default
      rows: 1
      cols: 2
      collapsed: false
      hideForGuests: false
    items:
      - title: BetterBachelor
        icon: favicon
        url: https://rumble.com/c/BetterBachelor
        id: 0_1956_betterbachelor
      - title: YouTube
        description: ''
        icon: favicon
        url: https://www.youtube.com/
        target: sametab
        id: 1_1956_youtube
      - title: 9anime
        icon: favicon
        url: https://9anime.to/home
        target: sametab
        id: 2_1956_anime
      - title: Rico
        icon: https://www.rico.com.vc/login/favicon.png
        url: https://www.rico.com.vc/login/
        id: 3_1956_rico
      - title: TradingView
        icon: favicon
        url: https://br.tradingview.com/chart/4sfvad0s/
        id: 4_1956_tradingview
      - title: Mercado Livre
        icon: >-
          https://http2.mlstatic.com/frontend-assets/ui-navigation/5.18.9/mercadolibre/favicon.svg
        url: https://www.mercadolivre.com.br/
        id: 5_1956_mercadolivre
      - title: AliExpress
        icon: favicon
        url: https://pt.aliexpress.com/
        id: 6_1956_aliexpress
      - title: Twitch
        icon: favicon
        url: https://www.twitch.tv
        target: newtab
        id: 7_1956_twitch
      - title: DropBox
        icon: favicon
        url: https://www.dropbox.com/home
        id: 8_1956_dropbox
      - title: Q-Dance
        icon: https://www.q-dance.com/static/images/favicon/favicon-32x32.png
        url: https://q-dance.com
        id: 9_1956_qdance
      - title: Android Find
        icon: favicon
        url: https://www.google.com/android/find
        target: newtab
        id: 10_1956_androidfind
  - name: Widgets
    widgets:
      - type: clock
        options:
          timeZone: America/Sao_Paulo
          format: pt-BR
          hideDate: false
        id: 0_727_clock
  - name: Tools
    icon: fas fa-cubes
    items:
      - title: Pi-Hole
        description: DNS ad-blocking
        icon: hl-pihole
        url: http://localhost:8000/admin/
        id: 0_529_pihole
      - title: Portainer
        icon: hl-portainer
        url: http://192.168.56.104:9000/
        target: newtab
        id: 1_529_portainer
      - title: Jenkins
        description: ''
        icon: hl-jenkins
        url: http://192.168.56.104:8000/
        id: 2_529_jenkins
      - title: KanBoard
        description: ''
        icon: hl-kanboard
        url: http://192.168.56.104:8080/
        id: 3_529_kanboard
      - title: Kibana
        icon: hl-kibana
        url: http://192.168.56.104:5601/app/apm
        id: 4_529_kibana
      - title: GoCD
        icon: si-gocd
        url: http://localhost:8153/go
        id: 5_529_gocd
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Internal
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Portainer
        icon: hl-portainer
        url: http://192.168.56.107:9000/
        id: 0_829_portainer
      - title: RabbitMQ
        description: Manager
        icon: hl-rabbitmq
        url: http://192.168.56.107:15672/
        id: 1_829_rabbitmq
      - title: Redis Commander
        icon: hl-redis
        url: http://192.168.56.107:8020/
        id: 2_829_rediscommander
