---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
headerStyle: clean
target: _self
layout:
  Media & Entertainment:
    style: row
    columns: 4
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
